version: '2.0'

services:
  nginx:
    image: nginx
    restart: always

    volumes:
     - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
     - "./etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
     - "./html:/usr/share/nginx/html:ro"

    ports:
     - "127.0.0.1:9080:80"
